// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyCxZ4pCsSyLsV3l1ySI6Pjiiia2uEsCU',
    appId: '1:410244285250:web:9f29b31949eb827708bedb',
    messagingSenderId: '410244285250',
    projectId: 'task-management-7722b',
    authDomain: 'task-management-7722b.firebaseapp.com',
    storageBucket: 'task-management-7722b.appspot.com',
    measurementId: 'G-YVGGP0V8X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRMUr0WM9gro8xdlOQWBn5tdWmjxU7IeY',
    appId: '1:410244285250:android:1f80893d2da1661508bedb',
    messagingSenderId: '410244285250',
    projectId: 'task-management-7722b',
    storageBucket: 'task-management-7722b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCViqmo9dqe3UGRt_hBJ6Y0w7bqJ5_6Sp0',
    appId: '1:410244285250:ios:3f82f20d7da1424c08bedb',
    messagingSenderId: '410244285250',
    projectId: 'task-management-7722b',
    storageBucket: 'task-management-7722b.appspot.com',
    iosBundleId: 'com.example.taskManagementNaderr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCViqmo9dqe3UGRt_hBJ6Y0w7bqJ5_6Sp0',
    appId: '1:410244285250:ios:ec4f03213587863308bedb',
    messagingSenderId: '410244285250',
    projectId: 'task-management-7722b',
    storageBucket: 'task-management-7722b.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyCxZ4pCsSyLsV3l1ySI6Pjiiia2uEsCU',
    appId: '1:410244285250:web:a7533aca39856fb308bedb',
    messagingSenderId: '410244285250',
    projectId: 'task-management-7722b',
    authDomain: 'task-management-7722b.firebaseapp.com',
    storageBucket: 'task-management-7722b.appspot.com',
    measurementId: 'G-ZH1W1VYXXK',
  );

}